name: .NET Framework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: nuget restore ./SampleGitHubActions.Test/SampleGitHubActions.Test.csproj -SolutionDirectory .

    - name: Build
      run: msbuild ./SampleGitHubActions.Test/SampleGitHubActions.Test.csproj /p:Configuration=Release

    - name: Find VSTest.console.exe
      id: vswhere
      run: |
        $vsTestPath = & 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' -latest -requires Microsoft.VisualStudio.PackageGroup.TestTools -find **\vstest.console.exe
        echo "##vso[task.setvariable variable=VSTEST_CONSOLE_PATH]$vsTestPath"

    - name: Run tests
      run: |
        $vstestPath = $env:VSTEST_CONSOLE_PATH
        & $vstestPath ./SampleGitHubActions.Test/bin/Release/SampleGitHubActions.Test.dll
      shell: pwsh
